version: "3.1"

services:
  client_app:
    container_name: vue
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ".:/app"
      # - "./node_modules:/opt/app/node_modules"
    ports:
      - "8080:8080"
    restart: on-failure
