version: '3.4'

services:
  app:
    container_name: app_vue
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "7000:3000"
    restart: on-failure
    tty: true
    stdin_open: true
